export const CHANGE_EMAIL_FIELD = "CHANGE_EMAIL_FIELD"
export const CHANGE_PASSWORD_FIELD = "CHANGE_PASSWORD_FIELD"
export const CHANGE_NAME_FIELD = "CHANGE_NAME_FIELD"
export const CHANGE_IMAGE_URL_FIELD = "CHANGE_IMAGE_URL_FIELD"

export const LOAD_USER = "LOAD_USER"
export const INCREMENT_USER_ENTRIES = "INCREMENT_USER_ENTRIES"

export const SIGNIN_REQUEST_PENDING = "SIGNIN_REQUEST_PENDING"
export const SIGNIN_REQUEST_SUCCESS = "SIGNIN_REQUEST_SUCCESS"
export const SIGNIN_REQUEST_FAILED = "SIGNIN_REQUEST_FAILED"
export const REGISTER_REQUEST_PENDING = "REGISTER_REQUEST_PENDING"
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS"
export const REGISTER_REQUEST_FAILED = "REGISTER_REQUEST_FAILED"
export const SIGN_OUT = "SIGN_OUT"

export const CLEAR_INPUT_FIELD = "CLEAR_INPUT_FIELD"
export const CLEAR_USER = "CLEAR_USER"
